### ISSUE TITLE
User Interface Refresh

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#1]
Inspired by https://walmartlabs.github.io/web-style-guide/

Features to include in new version:
- consider naming conventions
- integrate docs
- integrate code previews
- expand all menus in burger by default
- improve usability of interface
- create chopchop styles that are unique and separate to the site

**Comment by daveredfern** [comment]
@gazjoy we should limit the scope of this ticket to:
- create chopchop styles that are unique and separate to the site
- expand all menus in burger by default
- improve usability of interface

We should obviously take into consideration the other elements but right now this ticket is too large to accomplish in a reasonable time. I'll make the other points separate issues.
