### ISSUE TITLE
Make chopchop work from any sub folder

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#102]
Right now chopchop only works in root. Would be good in any sub folder.

Thanks @ejrowley .

**Comment by daveredfern** [comment]
@ejrowley @gazjoy think this was revered and it wasn't working. Can we get a fix for this please?

**Comment by gazjoy** [comment]
@daveredfern I think this is sorted. Will check now.

**Comment by gazjoy** [comment]
@daveredfern @ejrowley yep seems to work fine. @ejrowley not sure if this is an effect of the update but it needs a fix. https://github.com/getchopchop/chopchop/issues/112
