### ISSUE TITLE
Add Bridge CSS for WordPress/Magento

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#107]
As discussed with @jakecobley @mustardbees

**Comment by gazjoy** [comment]
@daveredfern I have started this, would be good to discuss further with you before committing anything to this repository.

**Comment by daveredfern** [comment]
@gazjoy should these be in a bridge folder and in chopchop by default but commented out in style.scss? I have a wordpress one already for this.

**Comment by gazjoy** [comment]
@daveredfern I also have a WordPress one! I thought it was just me assigned to this? The Magento one is almost there, we can refine over time too. Not sure if it should live in core though? Maybe a couple of Gists will do?

**Comment by gazjoy** [comment]
@daveredfern I have moved all my current bridge stuff to here:https://github.com/getchopchop/chopchop-sass-bridge

Over time this should slowly disappear.
