### ISSUE TITLE
Remove atomic design

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#108]
Remove atomic design as it isn't working well for us. The confusion between molecules and organisms is painful. Instead move to a more ITCSS:

![image](https://cloud.githubusercontent.com/assets/183473/19127051/522c1b5e-8b35-11e6-985e-b90dda7d6af9.png)

So the folder structure will be:
- Branding
- Helper
- Utility
- Base
- Component
- Demo

**Comment by gazjoy** [comment]
In next release 
https://github.com/getchopchop/chopchop/commit/e0db7bb5c4d8cc647e60d35a68389a6378b5d57c
and https://github.com/getchopchop/chopchop/commit/731fc50c2f4b3f266f72df25ac370cc67d84fa69

and
https://github.com/getchopchop/chopchop/commit/737b72ce38598cbe6e2c9d10400e8d898db48b21
