### ISSUE TITLE
Preview links are broken

### ISSUE THREAD

**Issue by mustardBees** [getchopchop/chopchop#112]

**Comment by gazjoy** [comment]
@ejrowley Help please! The preview links are broken in the current release. If its a quick fix do you think you can take a look as soon as possible? https://getchopchop.github.io/pattern/branding/index.html

We can do a point release to fix.

**Comment by daveredfern** [comment]
@ejrowley @gazjoy any joy on this one?

**Comment by gazjoy** [comment]
Fixed here thanks to @ejrowley https://github.com/getchopchop/chopchop/commit/b92af9aaf9eb63fff8a0023110bc1f7c01de14ea
