### ISSUE TITLE
Table classes need refining

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#116]
Some table classes such as `table--striped` required to be on `<table>` and others need to be wrapped such as `table--responsive`. These need refining and organising properly. Maybe table--responsive is really an overflow scroll utility?

**Comment by gazjoy** [comment]
i'll have a looksie here.

**Comment by gazjoy** [comment]
Ok fixed up here: https://github.com/getchopchop/chopchop/commit/632fc3cd1d9ab349b3b7ce3446305b8cafd03ed3

**Comment by daveredfern** [comment]
Thanks @gazjoy
