### ISSUE TITLE
Spacing issues across components and browsers

### ISSUE THREAD

**Issue by jakecobley** [getchopchop/chopchop#119]
Using percentages for margin-top/bottom like we do for grid gutter isn't supported in Firefox. It only works if the element which is `display: flex;` has an explicit height. 

Might be worth adding a fallback value in em?

**Comment by daveredfern** [comment]
@jakecobley We'll take a look.

We do have a fallback for this already for Edge, which I think you flagged before too. https://github.com/getchopchop/chopchop/blob/next/src/scss/helper/_grid.scss

It would appear that edge and firefox previously behaved correctly, inline with W3C but the spec changed to allow the % to be either zeroed or calculated. https://bugzilla.mozilla.org/show_bug.cgi?id=958714.

Firefox might be harder to fix. Maybe switch to something other than percentages is a better option moving forward? What do you think @gazjoy?

**Comment by daveredfern** [comment]
Also see here: http://stackoverflow.com/questions/33502702/flex-elements-ignore-percent-padding-in-firefox

**Comment by daveredfern** [comment]
I think I have a solution for this. If gutter only applies left and right spacing instead of all around. Then we remove the CSS that zeros the margin of the last item inside that column. Should naturally give it spacing.

What do you think @gazjoy ?

**Comment by daveredfern** [comment]
@gazjoy I think we've discussion making grid gutters only horizontal and to remove the collapsing of the margins. If we agree I can sort this?

**Comment by gazjoy** [comment]
Possible solution here: https://www.smashingmagazine.com/2016/11/css-inheritance-cascade-global-scope-new-old-worst-best-friends/

one to test.

**Comment by gazjoy** [comment]
@daveredfern I think we have solved this one now? Didnt we say we will avoid using percentage gutters?

**Comment by daveredfern** [comment]
@gazjoy it is still a bug but yes we fixed it by avoiding vertical gutters. So on content grid we use a % then product ones we use a fixed spacing. I will close this as we've worked around it.
