### ISSUE TITLE
Create demo data files

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#124]
Data is in woo! But would be good to have some demo ones:

- titles
     - product
     - blog
- prices
- images
- categories
     - product
     - blog
- colours
- sizes
- names

Think of any others @gazjoy @jakecobley ?

**Comment by gazjoy** [comment]
@daveredfern started this in here: https://github.com/getchopchop/chopchop/commit/3a9ca306bf57a9729f04f203c7bcd0f21ab230e8

We should discuss how we are going to tackle images before adding this. It might be part of the refactor #131 work.
