### ISSUE TITLE
jquery.cookie no longer maintained

### ISSUE THREAD

**Issue by jakecobley** [getchopchop/chopchop#126]
This isn't maintained anymore. https://github.com/carhartl/jquery-cookie. We should switch it out to this: https://github.com/js-cookie/js-cookie.

## Submit a feature request or bug report
- [ ] This is a feature request
- [x] This is a bug report

### Checklist:

- [x] I have read the [CONTRIBUTING](https://github.com/getchopchop/chopchop/blob/next/.github/CONTRIBUTING.md) document.
- [x] This request isn't a duplicate of an [existing issue](https://github.com/getchopchop/chopchop/issues)

**Comment by daveredfern** [comment]
Thanks @jakecobley will look into this.

**Comment by daveredfern** [comment]
@llapgoch Can you take a look at this? The cookie is used to remember the toggle state of the menu.

**Comment by gazjoy** [comment]
@andrew-smart you are on. This is used only on the ui at the minute. Let me know if I can help.
