### ISSUE TITLE
Improve logo pattern

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#129]
![image](https://cloud.githubusercontent.com/assets/183473/20051474/1a69eb32-a4c7-11e6-9136-a7f2ababe190.png)

I don't think this pattern needs any CSS by default. It should have that class in the HTML. If that is not possible because of a limitation of a CMS it should be in the bridge file.

**Comment by gazjoy** [comment]
@daveredfern ok So no css. I can sort this.

**Comment by gazjoy** [comment]
Sorted here: https://github.com/getchopchop/chopchop/commit/67831b1139f5112d1e7391277ac8a0b0ae973bee
