### ISSUE TITLE
Refactor PHP

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#131]
The PHP is becoming more and more of a mess. We need to bring it under control.

**Comment by daveredfern** [comment]
New folder structure:

```
data
inc -> framework
pattern
src
```

Inc becomes framework and encompasses everything that is chopchop code. The idea to make it easily upgradable.

Inside framework break down the files into more digestible nuggets.

**Comment by daveredfern** [comment]
Each pattern to exist as a folder with a base.php pattern. If a doc.md exists we want to pull that in. So an example:

```
pattern-name
pattern-name/1-base.php
pattern-name/2-variation.php
pattern-name/docs.md
```

It would be displayed something similar to this:

![image](https://cloud.githubusercontent.com/assets/183473/20060642/0140f88a-a4f4-11e6-9747-cb30e0890ea4.png)

So...

Title comes from folder name.
Docs comes from docs.md
Then each pattern is from each file.

**Comment by daveredfern** [comment]
Inside a pattern we want the following options (although an easy way to add them would be amazing).

```
Code: true / false (true by default)
```

This toggles whether the view code link is visible/

```
Class: .classname
```

**Comment by daveredfern** [comment]
Functions that work inside each pattern:

```
printPattern('name-of-pattern', $data);
getPattern('name-of-pattern', $data);
getData('file-name', 'section', num);
PrintData('file-name', 'section', num);
getSvg('location-name');
printSvg('location-name');
getUrl('location'); // gets base url
```

**Comment by daveredfern** [comment]
A config file in the root called config.php would be good. Here we can change the folder order and structure. This currently lives in an array at the bottom of functions.php.

**Comment by gazjoy** [comment]
Also getLink needs to be added in: #42

**Comment by gazjoy** [comment]
@daveredfern checkout the section-readme branch. @Triickii has done us a solid. Have a play/test and we can get this merged asap.
