### ISSUE TITLE
Template space above

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#132]
![image](https://cloud.githubusercontent.com/assets/183473/20059760/ae3025d4-a4ef-11e6-8cef-06406d364b08.png)

Templates are adding a space above. Only on templates.

**Comment by daveredfern** [comment]
This should get fixed with the php refactor part of #131. I'll keep this open until then because it is actually a bug.

**Comment by gazjoy** [comment]
This is going to be archived. Will be fixed with new PHP.
