### ISSUE TITLE
Make .select a component

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#134]
Title explains it. should be it's own file and component. not part of base.

**Comment by gazjoy** [comment]
@daveredfern I'll sort this one.

**Comment by gazjoy** [comment]
Also file upload that is styled.

**Comment by gazjoy** [comment]
Sorted: https://github.com/getchopchop/chopchop/commit/27f58355affa5aba01192711738bc0fbf1203ef4
