### ISSUE TITLE
Add max width to form elements

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#135]
Cap form widths to reduce the width of grids.

**Comment by daveredfern** [comment]
I had a thought. This will break errors so maybe a better solution is to add a max width the field groups. this would ensure the error is the same width.

**Comment by daveredfern** [comment]
@gazjoy I can sort this. Suggested max width? Could do `screen(xs,max)`?

**Comment by gazjoy** [comment]
@daveredfern yeh lets try it see how we go.

**Comment by daveredfern** [comment]
@gazjoy ok great, I'll sort this.

**Comment by daveredfern** [comment]
Done
