### ISSUE TITLE
Reset utility

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#137]
Margins are currently handled differently across components. I suggest margins should be on by default, grid gutter should be horizontal only.

@gazjoy suggests introducing a reset util. This could allow reset of margins, paddings and maybe more in the future. Along with the option to reset left, right, top, bottom specifically.

**Comment by gazjoy** [comment]
@daveredfern any other thoughts on this since the latest build?

**Comment by daveredfern** [comment]
@gazjoy i used this on raleigh but not on mymemory. feels like this would only exist if the patterns are poor?

**Comment by daveredfern** [comment]
Will close this for now. Might be required in the future but it can bubble up as a new issue.
