### ISSUE TITLE
Add hex to colours

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#149]
Add colour hex.

**Comment by gazjoy** [comment]
In here: https://github.com/getchopchop/chopchop/commit/1b4c0dc952077ecb82fa38bd0762a9cdb9b4d2b5

**Comment by daveredfern** [comment]
@gazjoy this doesn't work for contextual stuff. showing an error for me.

**Comment by gazjoy** [comment]
@daveredfern where are you seeing the error? https://getchopchop.github.io/pattern/branding/index.html

**Comment by gazjoy** [comment]
@daveredfern went mad again.
