### ISSUE TITLE
Remove Ico Moon Premium

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#15]
We need to swap out the premium icons with the free versions.

Swaps
arrow-down - circle-down
arrow-up - circle-up
arrow-left - circle-left
arrow-right - circle-right
basket - cart
grid - table2

Renames
star - star-full

Different Icons same name
zoom-in
zoom-out
image
search
lock
phone

**Comment by daveredfern** [comment]
We can use arrow-down, arrow-up, arrow-left, arrow-right for free. They're different to the currents but better than a circle version.

Revised list:

Swaps
basket - cart
grid - table2

Renames
star - star-full

Different Icons same name
zoom-in
zoom-out
image
search
lock
phone
arrow-down
arrow-up
arrow-left
arrow-right

**Comment by gazjoy** [comment]
@daveredfern this is done and merged into next.
