### ISSUE TITLE
Hex on colours break when using html colours

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#158]
![image](https://cloud.githubusercontent.com/assets/183473/20797080/4449bf28-b7d1-11e6-985d-27e1f39105ab.png)

When using a HTML colour such as `green` it breaks the hex colours on `branding/color`. Only works with hex colours. Something to do with not adding it to the array.

**Comment by gazjoy** [comment]
@daveredfern also breaks when using gradients.

**Comment by gazjoy** [comment]
@Triickii as discussed. We could do with 1 function that deals with all this.

At the moment the same code is output in 3 places.

pattern/branding/color/color.php
pattern/utility/color/fill.php
pattern/utility/color/text.php

**Comment by daveredfern** [comment]
A related issue is on this ticket: https://github.com/getchopchop/chopchop/issues/182
