### ISSUE TITLE
Allow multiple targets with data-cc-target toggles

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#16]
The ability to pass through multiple targets inside `data-cc-target` so we're able to activate multiple things with one click. Example usecase:

``` html
<a href="#" data-cc-target="item-1,item-2" data-cc-action="activate">Hello, world</a>

<div id="item-1"></div>
<div id="item-2"></div>
```

**Comment by gazjoy** [comment]
Merged here: https://github.com/getchopchop/chopchop/pull/27

**Comment by daveredfern** [comment]
@balloz @gazjoy This now splits on spaces. Cascades also now split on spaces. Example:

``` html
<a href="#" data-cc-target="item-1 item-2" data-cc-action="activate">Hello, world</a>
```

Done so spaces don't break the splitting function. @balloz suggested for consistency with standard html, such as class declarations.
