### ISSUE TITLE
Colour Groupings

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#160]
I think colours should be grouped like so:

- Primary palette: Main brand colours
- Secondary palette: Other colours, (example used on labels)
- Neutral palette: (greys, black, white)
- Social palette: (social networks)
- Contextual palette: (example used on alerts)

Seems fairly sensible, @daveredfern thoughts?

**Comment by daveredfern** [comment]
@gazjoy I like. Been using brand colours of MM too much when a secondary palette would be perfect.
