### ISSUE TITLE
Lovely Radio

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#162]
As we are already styling selects why not radios too?

http://codepen.io/triss90/pen/XNEdRe

Making the clickable area bigger seems to be the right trend:
https://designnotes.blog.gov.uk/2016/11/30/weve-updated-the-radios-and-checkboxes-on-gov-uk/

**Comment by daveredfern** [comment]
@gazjoy looks good. would be nice to have some larger ones for mobile especially.
