### ISSUE TITLE
Add keyboard interaction on modals and drawers

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#166]
be nice is esc worked on modals and drawers to close them.

**Comment by daveredfern** [comment]
@llapgoch is this something you could look at?

**Comment by gazjoy** [comment]
@llapgoch as discussed, chopchop.keyboard.widget.js This is the js I had for RSM but do what you feel is best please lad.

```js
    $(document).keyup(function(e) {
         if (e.keyCode == 27) {
             $('#drawer-left').chopchop('toggle', 'deactivate');
             $('#drawer-right').chopchop('toggle', 'deactivate');
             $('#modal').chopchop('toggle', 'deactivate');
        }
    });

**Comment by gazjoy** [comment]
@daveredfern @gazjoy

@llapgoch wrote:

Add the attribute `data-cc-toggle-keyboard-close="true"` to elements to support keyboard closing
The keyboard `keyCode` can also be overridden using `data-cc-toggle-keyboard-close-key-code="27"`.

When instantiating with javascript, use option keys `keyboardClose`, and `keyboardCloseKeyCode`.

**Comment by gazjoy** [comment]
Done in #203 and documentation updated.
