### ISSUE TITLE
Placeholder image function

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#172]
A placeholder image function would be good. Default to use pims so we can switch it out.

**Comment by gazjoy** [comment]
http://pims.iweb.co.uk/docs/
http://pims.iweb.co.uk/500x500?fg=ff0000&bg=000000

**Comment by daveredfern** [comment]
I suggest:

`getPlaceholder($height, $width, $fg, $bg, $text);`

likewise:

`printPlaceholder($height, $width, $fg, $bg, $text);`
