### ISSUE TITLE
Output SVG's as separate files

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#18]
Currently all svgs are combined into one file. It would be good if they were outputted as separate files – one per folder. This will stop the files being so large. The cards are especially big and most the time they're not used.

**Comment by jakecobley** [comment]
Already have a working version of this. Just some tweaking to do. I'll push current progress to a branch.

**Comment by daveredfern** [comment]
@JakeCobley going to do this soon? :)

**Comment by jakecobley** [comment]
90% done :) Just got to clean it up. Will add a WIP PR later today?

**Comment by jakecobley** [comment]
Just waiting on PR #53 to be merged before I can submit the PR for this issue.

**Comment by daveredfern** [comment]
@JakeCobley this has been merged. Thanks.

**Comment by JakeCobley** [comment]
PR #57
