### ISSUE TITLE
Refactor files and php

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#20]
The functions.php needs an overhaul, its just a dumping ground for everything at the minute and is hard to understand.

Also as part of this we'd like to move these files/directories into the root

```
html/index.php
html/.htaccess
html/inc
```

and rename the html directory to pattern.

Ultimately the structure should look like this:

```
pattern
src
inc
index.php
```

**Comment by gazjoy** [comment]
I think the folder `html` needs changing too, sorry ;-) @daveredfern maybe static was a better name!

**Comment by daveredfern** [comment]
@gazjoy it will become pattern now, not HTML? then the route will be the accessibly URL so no weird redirecting. Pattern is the best name for it's content.
