### ISSUE TITLE
Integrate docs

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#21]
We would like to integrate code previews and docs into ChopChop. This is part of the redesigned #1 interface but I have separated it because I suspect it will need larger structural changed behind the scenes.

I see that by integrating docs we now need a new file per pattern. I propose the following structure for each pattern:

```
pattern-name
pattern-name/pattern.php
pattern-name/docs.md
```

For example:

```
// this is default or base
card
card/pattern.php
card/docs.md

// variations live in nested folders
card/bordered
card/bordered/pattern.php
card/bordered/docs.md
```

I have attached a basic screenshot of the proposed layout.

![unspecified](https://cloud.githubusercontent.com/assets/183473/16514251/9f847c1c-3f62-11e6-9460-edd47e3e895d.png)

**Comment by daveredfern** [comment]
New thinking is we have one doc per folder. Then all modifiers live together without docs. This will reduce the overload.  Here is a good example working: https://walmartlabs.github.io/web-style-guide/#components.

So would be something like this for the folder structure:

```
card/docs.md
card/01-base.php
card/02-bordered.php
card/03-featured.php
```

This would mean that all top levels need to give in a folder so things like breadcrumb that currently lives in `molecule/breadcrumb.php` would need to live in `molecule/breadcrumb/base.php`. I think this is a reasonable compromise and doesn't add too much overhead. In fact, might make the organisation clearer.

So the layout would be more like this:

![artboard](https://cloud.githubusercontent.com/assets/183473/16651585/cdd6929c-443c-11e6-9c29-a312942061d3.png)

**Comment by gazjoy** [comment]
+1 I like this @daveredfern

**Comment by gazjoy** [comment]
@daveredfern not sure if this is worth a look: https://github.com/filamentgroup/X-rayHTML

**Comment by daveredfern** [comment]
@gazjoy definitely, looks exactly what we want.

**Comment by daveredfern** [comment]
I am going to close this as it now comes under the https://github.com/getchopchop/chopchop/issues/131 ticket.
