### ISSUE TITLE
Function to return array of classes in stylesheet

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#211]
Same as colours but returns an array of anything we want.

not sure what to call this function so open to ideas.

`getCss('g-col-lg')`

this would return an array of anything with g-col-lg in it.

I managed to do a regex that might help `.([^\s,{]+)` or `.g-col-([^\s,{]+)`.

I can manually print them out once we have the array where ever we want them to appear.

**Comment by Triickii** [comment]
@daveredfern has this been done now?

**Comment by daveredfern** [comment]
@Triickii yes, feel free to refactor it. If you look in utilities you can see what we're trying to achieve.

**Comment by gazjoy** [comment]
done in #213
