### ISSUE TITLE
Add section utility

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#23]
Add a section utility to ensure the spacing between blocks on a website are consistent. It might be nice to try using vw or vh as a measure so it is responsive.

We will need to experiment in Codepen to make sure we get this right. Ideally we want them margins so they overlap correctly.

**Comment by gazjoy** [comment]
Added in next branch: https://github.com/getchopchop/chopchop/commit/0929332f7c0cad2fb066d52ab46451fce356143b
