### ISSUE TITLE
Add input file upload to form atoms

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#24]
We're missing file upload from the form atoms. Not used often but should be in the base.

**Comment by gazjoy** [comment]
Good catch @daveredfern. http://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/

**Comment by daveredfern** [comment]
Nice @gazjoy. I like the idea of converting it to a button. They're damn ugly by default!

**Comment by gazjoy** [comment]
@daveredfern ok this is now queued up on the next branch, here is the commit: https://github.com/getchopchop/chopchop/commit/e5f7d783d57354df34767f01bf1588f1b1034065

Sorry forgot to ref the error in the commit. 😞
