### ISSUE TITLE
Add responsive headings

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#30]
Currently we don't scale headings, we leave it per site. It's hard to get them right so a base to tinker from would be useful.

**Comment by daveredfern** [comment]
Experiment with using mixins to accomplish this with less code.

**Comment by gazjoy** [comment]
https://codepen.io/gazjoy/pen/mEXGYd

**Comment by daveredfern** [comment]
This has been added. https://github.com/getchopchop/chopchop/commit/ba73f6205ff44150c725d047c709ce375afcb333
