### ISSUE TITLE
Table borders need revising

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#35]
The borders on tables seem a little messed up. We have thick borders below the heading and below the footer. They should be above the footer though.

![image](https://cloud.githubusercontent.com/assets/183473/17020732/27b883de-4f3b-11e6-9123-29a7ade8eb88.png)

![image](https://cloud.githubusercontent.com/assets/183473/17020734/2cc4b762-4f3b-11e6-9d12-39b781d5fa6c.png)

![image](https://cloud.githubusercontent.com/assets/183473/17020739/324515c4-4f3b-11e6-9fec-77fef4220717.png)

![image](https://cloud.githubusercontent.com/assets/183473/17020745/37b0a636-4f3b-11e6-901e-ed9a16a0feb7.png)

**Comment by gazjoy** [comment]
Fixed here: https://github.com/getchopchop/chopchop/commit/45e32ad1b1c2d7aff68e40b99d0c5b97442ed267
