### ISSUE TITLE
Data Integration

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#4]
Idea of using a json or yaml file in the repository.

The problem with that approach is that it is not very dynamic and would be hard for a client to update.
An alternative approach is to pull the data in from somewhere and let it be editable, this would involve having a simple service to store and send the data and some javascript in chopchop. The cool part will be that we could store other data to - like annotations.

**Comment by gazjoy** [comment]
It would be nice to have a global config to be able to pass through things like the site name, url, client contact info. This information could appear in the header of the index.

**Comment by daveredfern** [comment]
Our current thinking, to expand on this, is the use yaml files to store data such as product titles, blog posts, prices, image paths. I suggest this is in a folder called data in the root of chopchop. Inside that a file for each data. e.g. blog-title.yml.

Then with functions we can retrieve them such as:

``` php
getData('blog-title');
printData('blog-title'); // prints out
```

This is probably enough for now. Later we can expand if we feel necessary.

**Comment by daveredfern** [comment]
Maybe we could target things inside the yaml files too. For example we could have a global.yaml file in our data and then do:

``` php
getData('global', 'site-name');
```

This would retrieve the site name inside the global yml file. If we just did the following it would retrieve a random entry:

``` php
getData('global');
```

Same would apply to blog titles, we could do either of the following:

``` php
getData('blog-title');
getData('blog-title', 5); // return 5th item
```

Obviously this is all open to ideas. Just throwing thoughts after speaking to @gazjoy and @ejrowley over the last few months.

**Comment by daveredfern** [comment]
global.yml
- site-name
- tagline
- tel
- email

product-title.yml
blog-title.yml
product-title.yml
price.yml
author.yml
blog-cateories.yml
product-catergories.yml
color.yml
size.yml
number.yml

function:
name of file
specific item (by site-name or 3)
random / in order

```
<p class="logo"><?php printData('global', 'site-name'); ?></p>
<p><?php printData('price'); ?></h2>
<h2><?php printData('blog-title', 2); ?></h2>
<h2><?php echo getData('blog-title', 2); ?></h2>
```

```
<?php for($i=0;$i<5;$i++) : ?>
<h2><?php printData('blog-title', $i); ?></h2>
<?php endfor; ?>
```

**Comment by daveredfern** [comment]
@JakeCobley reckon we can get some basic integration this month? Nothing fancy, we can start small.

**Comment by jakecobley** [comment]
@daveredfern yeah defiantly. Aiming to get a ruff implementation shortly. Will be mapping everything out Thursday so will likely give you a shout then.

**Comment by daveredfern** [comment]
@JakeCobley great!

**Comment by jakecobley** [comment]
PR #122

**Comment by daveredfern** [comment]
```
// Grabs the site name from the site name variable in the global.yml file in the data directory.
<?php printData('global', 'site-name'); ?>

// Grabs a random entry from the title object within the blog object in the blog.yml file in the data directory.
<?php printData('blog', 'title'); ?>

// Grabs the first (starts from 0) title from the title object within the blog object in the blog.yml file in the data directory.
<?php printData('blog', 'title' 0); ?>

// Grabs the second (starts from 0) author from the author object within the blog object in the blog.yml file in the data directory.
<?php printData('blog', 'author', 1); ?>

// Grabs the second (starts from 0) blog title from the blog-title object in the blog-titles.yml file in the data directory.
<?php printData('blog-title', 1); ?>

// Grabs a random entry from the blog-titles object in the blog-titles.yml file in the data directory.
<?php printData('blog-title'); ?>
```
