### ISSUE TITLE
Investigate vertical spacing on buttons

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#41]
I am generally noticing they seem to sit a little low when using default fonts. Might be something to investigate. Very noticeable when adding an SVG icon.

![image](https://cloud.githubusercontent.com/assets/183473/17049153/505d42ae-4fe3-11e6-85b0-10a33a16fcb1.png)

![image](https://cloud.githubusercontent.com/assets/183473/17049162/70badf52-4fe3-11e6-8e55-7f90da317e89.png)

**Comment by daveredfern** [comment]
This is a font issue with San Fransisco on Apple devices. I recommend not fixing it. We will only cause issues in other browsers. As @gazjoy noticed, setting to pixel values fixes the issue.

Now our default font uses system fonts we will have this issue on most sites that don't use an custom font.

Probably nothing to do here @gazjoy ?

**Comment by gazjoy** [comment]
[http://jgthms.com/in-css-use-pixels-not-em.html#just-use-pixels](url)
