### ISSUE TITLE
getLink function to link templates together

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#42]
A getLink function might be nice so we can make the templates feel more like a website. We would be able to link news items to news detail, product items to product detail etc.

What do you think @gazjoy ?

**Comment by gazjoy** [comment]
@daveredfern yeh i think we need something but it all needs tying into the global config so it might be worth discussing as a group.

I have already been doing this using:

`<?php echo getUrl('html/template/basket'); ?>`

but obviously this isn't ideal as it needs to contain the root folder name.

**Comment by jakecobley** [comment]
Is issue still relevant now templates have been binned?

**Comment by jakecobley** [comment]
Issue: #128 explains we do still need this :)

**Comment by daveredfern** [comment]
@jakecobley I agree. I hope this can come under here too https://github.com/getchopchop/chopchop/issues/131.

**Comment by gazjoy** [comment]
It would be good for it to work like `printPattern` but return the absolute URL instead.

Function:
`getLink('location', $preview=boolean);`

The preview option would add ?preview to the link which removes chopchop interface.

Example:
`getLink('template/homepage', true);`

`printLink` would also be a good option.
