### ISSUE TITLE
Clean up chopchop interface

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#43]
We can probably remove cc-box now as we have u-block in the core interface. We can also look at tidying the colours. I know we go in circles but on brand shades of grey would be nice I think.

What do you think @gazjoy ?

**Comment by gazjoy** [comment]
@daveredfern yep sensible.

**Comment by daveredfern** [comment]
Cool. Shouldn't be a big job. Hopefully squeeze it in before next release :)

**Comment by gazjoy** [comment]
I have removed the cc-box in this commit: https://github.com/getchopchop/chopchop/commit/2af75a7f0b3c567532cb4d2278abebe395d25da8
