### ISSUE TITLE
Add top and bottom only section classes

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#48]
We have section classes that are applied to top and bottom. It would be useful to have top and bottom only ones also.

**Comment by gazjoy** [comment]
Ok I have added top and bottom classes in this commit. https://github.com/getchopchop/chopchop/commit/17a4d6873ef0727ef0087d26343a5e417a2f27d8

**Comment by gazjoy** [comment]
Need to add demo HTML.

**Comment by gazjoy** [comment]
Demo added in here: https://github.com/getchopchop/chopchop/commit/980385e3378afaa2d5d617cc951892a166e99c78
