### ISSUE TITLE
Improve menu UI

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#52]
Show the menu to the left without overlaying any other content. Then add an overlay to other content so when you click it automatically closes. Lovely.

**Comment by gazjoy** [comment]
Done in here: https://github.com/getchopchop/chopchop/commit/e3b3eb18db3b8046356cdd81a2eb90eb6d5fffa0

@daveredfern to add js cookie to set menu display.

**Comment by daveredfern** [comment]
Done some here https://github.com/getchopchop/chopchop/commit/37bbe7a4f7fc0165b7aa1e02880c3e4b56a909fc
