### ISSUE TITLE
Rename include files

### ISSUE THREAD

**Issue by jakecobley** [getchopchop/chopchop#55]
We have `styles.php` which is included in the head and `scripts.php` which is included in the footer.

Maybe they should be renamed so they refer to their location rather than their contents.

For example, Element queries require scripts to be loaded in the head.

**Comment by gazjoy** [comment]
@JakeCobley Thanks for this. It will be in the next release. Commit it here: https://github.com/getchopchop/chopchop/commit/9e40854f758edefb9f03e75af95c4b7a053c7274
