### ISSUE TITLE
Check gulp is recognising new files

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#58]
Since the change in gulp version I am not sure it is recognising new files. Tried Sass and Scss files and neither seem to be noticed. Might be me!

Let me know if you want a demo @JakeCobley.

**Comment by jakecobley** [comment]
You right, there are issues :/

The watching new files issue is a Gulp issue, [see here](https://github.com/gulpjs/gulp/issues/651), not a ChopChop issue. 

The issue has been resolved in Gulpv4. I'm working on updating back to Gulpv4, properly this time, at the moment. Hold tight!

**Comment by jakecobley** [comment]
@daveredfern just tiding this up and will be ready to submit a PR.

**Comment by jakecobley** [comment]
This is fixed in PR #93

**Comment by daveredfern** [comment]
Amazing, thanks @jakecobley
