### ISSUE TITLE
Add scripts and demo JavaScript into file but comment them out

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#60]
Whenever I come to use enquire or element queries it is a mess around to grab the right snippets. Might be nice to show some basic examples but comment them out. Won't compile then but super useful for out the box.

Thoughts @gazjoy?

**Comment by gazjoy** [comment]
OK this is a nice idea. I have added it in this commit: https://github.com/getchopchop/chopchop/commit/5ebad895112ca06b8574863126e377b0ac2e9b52
