### ISSUE TITLE
Full width grid with gutter causes horizontal scrolling

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#61]
Title explains it. Full width grid with gutter causes horizontal scrolling. Need to figure how we're doing gutters to stop this.

**Comment by daveredfern** [comment]
Forgot to mention. This is 100% width of page with no containers etc.

**Comment by gazjoy** [comment]
No real solution but a good workaround would be to wrap a `u-clearfix` around the grid.

Solved for now so closing unless it happens again and we can revisit.
