### ISSUE TITLE
Can Toggles be More User Friendly?

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#66]
We're really struggling to use toggles. They're just not working for us. The main problem is we're unable to activate and deactivate things at the same time. It makes any slight customisation impossible with toggles.

I propose we remove data-cc-action and replace it with:

`data-cc-activate`
`data-cc-deactivate`
`data-cc-toggle`

Then we can pass ID through to these data attributes.

Cascading is still handy and could (hopefully) work as originally implemented.

The benefit of this is we can then activate and deactivate items as we wish.

Thoughts @gazjoy @balloz ?

**Comment by gazjoy** [comment]
@daveredfern agreed, either we change or write some clear documentation and code demos. We are desperate for documentation on this.

**Comment by daveredfern** [comment]
@gazjoy @balloz I think it needs changes to simplify it. If that means it is less flexible, I am happy with that. I am finding it harder to implement toggles than it is to write custom JS. The custom JS is often only a few lines long too.

Maybe a meeting required to take the last few sites using chopchop and screenshot all the usecases for toggles.

**Comment by gazjoy** [comment]
@daveredfern worth a read. Lots of accessibility that we currently dont have and no dependency in jQuery.

http://hugogiraudel.com/2016/10/13/you-might-need-javascript/
https://github.com/edenspiekermann/a11y-dialog
https://github.com/edenspiekermann/a11y-toggle

**Comment by gazjoy** [comment]
@daveredfern found this little gem: https://bitsofco.de/the-target-trick/ Support is solid: http://caniuse.com/#search=%3Atarget

**Comment by daveredfern** [comment]
@gazjoy what are we doing with this? Don't want this to just sit here for months.

**Comment by gazjoy** [comment]
@llapgoch is currently re writing the js toggles using a jQuery widgetised approach.

**Comment by gazjoy** [comment]
@llapgoch Does adding aria landmarks affect you? https://24ways.org/2015/how-tabs-should-work/

**Comment by gazjoy** [comment]
This is now in: https://github.com/getchopchop/chopchop/commit/bf1a354263ec0d9bbd7f5afb6269231473b5de68
