### ISSUE TITLE
Should we remove flags

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#67]
I am struggling to see a point for flags since we improved grids. The only place I use flags is for search input / buttons. Everywhere else I generally want a card to flag scenario so grids work really well.

Wondering if we should just have card, which is kinda like a styled box.

Thoughts @gazjoy @JakeCobley ?

Thanks,

Dave.

**Comment by jakecobley** [comment]
I've only ever used card to flags. Never used flags by itself.

**Comment by gazjoy** [comment]
@daveredfern we have been here before, we discussed it then maybe even removed it and put it back? Maybe its time to look at a more flexible way to use the flexbox mixin? If we got it right then grid could use it too as an underlying structural thing.

```
@include flexbox(center, space-between);
```

I have used flags but do find i'm over styling them per use case to make them do what I need.

**Comment by daveredfern** [comment]
@gazjoy @JakeCobley 

Flags were useful pre bootstrap style grids. Generally I am finding I want them stacked on mobile, 50/50 on small screens then 33/66 on larger ones. Grids are perfect for this.

I now find myself using card as a styling element. Such as this is a card with a grid inside:
![image](https://cloud.githubusercontent.com/assets/183473/17859569/07829b30-6882-11e6-87a2-11b16fa5e5e9.png)

This is not a card because they're just stacked elements:

![image](https://cloud.githubusercontent.com/assets/183473/17859637/4bed6534-6882-11e6-9407-0a4c403cef04.png)

Card is becoming a styled box for me. Everything uses grids for me or it's a bespoke pattern.

What is the usecase of flags?

I also agree something to operate flexbox in the background would be good. Would also help with backwards compatibility if ever required.

**Comment by daveredfern** [comment]
Moved this for September release. Requires more discussion.

**Comment by gazjoy** [comment]
Ok so after much discussion and testing we have decided to keep flags and make our underlying flag and grid mixins tidier by using a set of well used flexbox mixins.

@include flex;
@include flex-wrap(wrap);
@include flex-direction(column);
@include align-items(center);
@include justify-content(space-between);

**Comment by gazjoy** [comment]
Completed in several commits upto: https://github.com/getchopchop/chopchop/commit/84c385cf03d74c9d8321e057d770c491bab54213
