### ISSUE TITLE
Shape mixin HTML demos don't show anything

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#69]
We removed the original classes that were used to display shapes. We need to readd them in so the demos appear correctly.

![image](https://cloud.githubusercontent.com/assets/183473/17859459/9a11c030-6881-11e6-97f3-5413b0b4df70.png)

**Comment by gazjoy** [comment]
@daveredfern It looks like something may have gone wrong in the merge with ui.

**Comment by daveredfern** [comment]
Fixed https://github.com/getchopchop/chopchop/commit/85e399fa3cc8a62333fe651a6158e6308a26f404
