### ISSUE TITLE
Run go demo site script

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#74]
Hi @gazjoy 

can you run the demo site script please to update to the latest version? Not sure what the commands are?

Might be worth a quick wiki with steps?

Thanks,

Dave.

**Comment by gazjoy** [comment]
@daveredfern ok done now. It was on here: https://github.com/getchopchop/chopchop/pull/45

I've created a [wiki page](https://github.com/getchopchop/chopchop/wiki/Publishing) for publishing.
