### ISSUE TITLE
Embed Containers http

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#76]
https://getchopchop.github.io/html/utility/index.html#section-embed-container

Embed containers need protocol relative url to stop content being blocked on the demo site.

**Comment by daveredfern** [comment]
The urls are pointing to // so must be something else. Maybe the publish process?

**Comment by gazjoy** [comment]
@daveredfern I have hard linked them to https, this should sort the problem. https://github.com/getchopchop/chopchop/commit/1acdbce47c134fee76dd06b7f4b3702e5a04cf45

Needs a cursory check once next release is published.
