### ISSUE TITLE
Investigate font display

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#77]
https://css-tricks.com/font-display-masses/

Font display loads the web safe font first. Then the custom one. Makes page render quicker.

Worth looking into?

**Comment by gazjoy** [comment]
@daveredfern looks good. Definitely worth investigating.

**Comment by gazjoy** [comment]
More reading to do https://www.zachleat.com/web/comprehensive-webfonts/

**Comment by daveredfern** [comment]
@gazjoy this is probably a backlog thing? Maybe we should setup a project board.

**Comment by gazjoy** [comment]
Will revisit this if crops up again.
