### ISSUE TITLE
Permalink link extra slashes in URL

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#78]
When clicking permalink extra slashes appear in the URL.

**Comment by daveredfern** [comment]
Can you have a look at this @ejrowley ?

**Comment by daveredfern** [comment]
Permalink has now been removed but this still happens on the preview link.

**Comment by daveredfern** [comment]
Sorted https://github.com/getchopchop/chopchop/commit/9d6da0b4b405a560abd4f1584712dbeb59a166cc
