### ISSUE TITLE
Add EditorConfig

### ISSUE THREAD

**Issue by jakecobley** [getchopchop/chopchop#82]
It might be worth us using [EditorConfig](http://editorconfig.org/) to maintain consistent coding styles between collaborators.

You can see a list of big name projects which also use EditorConfig (ie. Bootstrap) [here](https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig)

**Comment by jakecobley** [comment]
PR #83

**Comment by daveredfern** [comment]
Merged into next. Thanks @JakeCobley  :)
