### ISSUE TITLE
Range Output IE11

### ISSUE THREAD

**Issue by gazjoy** [getchopchop/chopchop#9]
atom/form range output doesn't update in IE11.

**Comment by daveredfern** [comment]
Found this which covers all our basis. Might be worth investigation. http://brennaobrien.com/blog/2014/05/style-input-type-range-in-every-browser.html.
http://codepen.io/chriscoyier/pen/FtnAa

Can add the numbers with javascript class to make it more robust across browsers.

**Comment by daveredfern** [comment]
Fixed! https://github.com/getchopchop/chopchop/commit/51435b1a59bc3a71d47076db1af9d1e9ccd78a77
