### ISSUE TITLE
Should we rename Icons folder

### ISSUE THREAD

**Issue by jakecobley** [getchopchop/chopchop#91]
We're moving towards most of our images being SVG's, logo's etc, not just icons. Does 'icons' still fit?

**Comment by daveredfern** [comment]
@jakecobley I agree. maybe vector instead? What do you think @gazjoy ?

**Comment by gazjoy** [comment]
@daveredfern sure. Its just fluff.

**Comment by daveredfern** [comment]
@gazjoy @jakecobley we spoke about this and decided to leave it. Are we changing or not? :)

**Comment by jakecobley** [comment]
I think it would be nice to change it, something like 'vectors' that @daveredfern suggested is a better representation of what lives in the directory. But if anyone's against it it doesn't matter either. 'Icons' is still relevant.

**Comment by daveredfern** [comment]
@jakecobley don't think anyone is against it so go for it :)

**Comment by jakecobley** [comment]
PR #114

**Comment by daveredfern** [comment]
All done @jakecobley. Thanks!
