### ISSUE TITLE
Keep versioning consistent

### ISSUE THREAD

**Issue by jakecobley** [getchopchop/chopchop#92]
Ideally we should keep the version number up to date in the 'package.json' file.

**Comment by daveredfern** [comment]
@jakecobley agreed. @gazjoy we should create a 'go live' style document that outlines everything we need to do each month. Should include tests, version number updates etc?

**Comment by gazjoy** [comment]
@jakecobley @daveredfern will be sorted in next release v1.4.0 https://github.com/getchopchop/chopchop/commit/fe1b95509168e15e216838e154dd4d2ff85a9449
