### ISSUE TITLE
Use .github folder

### ISSUE THREAD

**Issue by jakecobley** [getchopchop/chopchop#94]
The CONTRIBUTING.md file as well as Issue and PR template files (Once we add them) should be contained within the .github folder.

This helps keep the root a little cleaner and keeps the repo consistent with GitHub.

**Comment by daveredfern** [comment]
@jakecobley sounds good with me. @gazjoy good for you?

**Comment by gazjoy** [comment]
@jakecobley yeh fine, feel free to do this. :-)

**Comment by jakecobley** [comment]
Done this in PR #98. Made a base on the documents, mostly taken from bootstrap and various templates from a google search. Feel free to edit these if you think they don't quite suit the project.

**Comment by daveredfern** [comment]
@jakecobley thanks! committed to next now.
