### ISSUE TITLE
Remove permalink

### ISSUE THREAD

**Issue by daveredfern** [getchopchop/chopchop#96]
@gazjoy mentioned it, adding for a reminder. Should permalink be removed? Is preview good enough?

**Comment by jakecobley** [comment]
What even is permalink used for? Never used it myself

**Comment by daveredfern** [comment]
@jakecobley the idea was so people could send each other links to a specific pattern. Copying the URL won't work if you scroll as the hash isn't updated. I think the preview link is enough.

**Comment by daveredfern** [comment]
Sorted https://github.com/getchopchop/chopchop/commit/bde80825bd9976a2f34119b28f3cf373653d7277
